/**
 * A machine-readable format for specifying errors in HTTP API responses based on https://tools.ietf.org/html/rfc7807.
 */
export interface ProblemDetails {

    /**
     * A URI reference [RFC3986] that identifies the problem type. 
     * This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type 
     * (e.g., using HTML [W3C.REC-html5-20141028]). 
     * When this member is not present, its value is assumed to be "about:blank".
     */
    type?: string;

    /**
     * A short, human-readable summary of the problem type. 
     * It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization
     * (e.g., using proactive content negotiation; see [RFC7231], Section 3.4).
     */
    title?: string;

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;

    /**
     * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
     */
    instance?: string;

    /**
     * The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
     */
    status?: number;

    /**
     * A unique identifier to represent a request in ASP.NET Core trace logs.
     */
    traceId?: string;

    /**
     * Gets the validation errors associated with this instance of ProblemDetails.
     */
    errors?: Record<string, string[]>;

    /**
     * 
     */
    [key: string]: unknown;
}

/*
// https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.problemdetails?view=aspnetcore-6.0
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
  "title": "An error occurred while processing your request.",
  "status": 500,
  "traceId": "00-330d73096d49e6a561d1422e355e9720-95889ed30f285704-00"
}

// https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.validationproblemdetails?view=aspnetcore-6.0
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-7ce36b7e0f395a48fb132b194ead79eb-b1b296f394a57968-00",
  "errors": {
    "Email": [
      "'Email' must not be empty.",
      "'Email' is not a valid email address."
    ],
    "Password": [
      "'Password' must not be empty.",
      "Password is not strong enough"
    ],
    "GivenName": [
      "'Given Name' must not be empty."
    ],
    "FamilyName": [
      "'Family Name' must not be empty."
    ]
  }
}
*/
